name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      run: yarn install

    - name: Build
      run: yarn build

    - name: Unit Test
      run: yarn test:ci

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1